[package]
name = "markdown"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = "0.2.50"
pulldown-cmark = "0.8"
